config/routes.rb
VirginiaFIRST::Application.routes.draw do

  resource :account, controller: "accounts", only: [:show, :edit, :update, :destroy], path_names: {edit: "settings"}

  scope module: 'accounts', path: 'account' do
    resource :profile, controller: "profiles", path: "personal", only: [:edit, :create, :update], as: "personal_profile"
    resource :background, controller: "profiles", only: [:edit, :create, :update], as: "background_profile"
    resource :volunteer, controller: "profiles", only: [:show, :edit, :update], as: "volunteer_profile"
    resource :mentor, controller: "profiles", only: [:show, :edit, :update], as: "mentor_profile"
    resource :experience, controller: "profiles", only: [:edit, :update], as: "experience_profile"
    get 'events' => 'registrations#index', as: 'my_events'
    delete 'events/:id' => 'registrations#destroy', as: 'delete_my_event'
  end

  namespace :ambassador do
    resource :registrations, path: 'register', only: [:new, :create, :show]
  end

  devise_for :users, controllers: {omniauth_callbacks: "omniauth_callbacks"}

  get 'home/events', as: 'upcoming_events'
  get 'home/faq', as: 'faq_home'
  get 'home/mentor', as: 'mentor_home'
  get 'home/volunteer', as: 'volunteer_home'

  get '/admin', to: redirect('/admin/events')
  scope module: 'admin', path: 'admin', as: 'admin' do
    scope path: '(/:program)' do
      resources :events
      resources :games
      scope module: 'volunteer', path: 'volunteer', as: 'volunteer' do
        resources :roles
      end
    end

    resources :skills
    resources :profiles, only: [:index, :show]
  end

  scope module: 'volunteer' do
    scope path: '(/:program)' do
      resource :registrations, path: 'register', as: 'volunteer_registration', only: [:new, :create, :show]
      resources :events, only: [:index, :show] do
        get 'profiles' => 'profiles#index'
        get 'reports/crew_break_down' => 'reports#crew_break_down', as: 'volunteer_break_down_report'
        get 'reports/nametags' => 'reports#nametags', as: 'volunteer_nametags_report'
        get 'reports/shirts' => 'reports#shirts', as: 'volunteer_shirts_report'
        get 'email_blast' => 'email_blast#show', as: 'email_blast'
        resources :check_in
      end
    end
    resources :assignments
    get 'profiles/:id' => 'profiles#show', as: 'profile'
  end

  root :to => 'home#index'

end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :game
  has_many :positions, -> { includes(:role).order('volunteer_roles.title') }, class_name: Volunteer::Position
  belongs_to :program, class_name: "FirstProgram"
  has_many :roles, -> { uniq }, class_name: Volunteer::Role, through: :positions
  has_many :volunteer_registrations, class_name: Volunteer::Registration
  has_many :volunteer_profiles, through: :volunteer_registrations, source: :profile

  scope :sorted, ->(order='ASC') { order("starts_at #{order}") }
  scope :upcoming, -> { where("starts_at > ?", Date.today).order("starts_at ASC") }

  attr_accessible :name, :participant_limit, :program_id, :code
  attr_accessible :setup_at, :starts_at, :teardown_at
  attr_accessible :city, :state, :street, :venue, :zip
  attr_accessible :positions_attributes

  accepts_nested_attributes_for :positions, allow_destroy: true

  validates_presence_of :name, :program, :code
  validates :code, length: { minimum: 2, maximum: 10 }
  validate :address_is_provided

  geocoded_by :full_address
  after_validation :geocode

  def count_unfilled_positions
    Volunteer::Position.
        joins("LEFT OUTER JOIN volunteer_assignments ON volunteer_assignments.position_id = volunteer_positions.id").
        group("volunteer_positions.id, volunteer_positions.event_id, volunteer_positions.needed_count").
        select("volunteer_positions.id, needed_count as needed, count(volunteer_assignments.id) as assigned").
        where({event_id: id}).having("count(volunteer_assignments.id) < needed_count")
  end

  def fullfillment
    total_filled_positions.to_f / total_positions_required.to_f
  end

  def full_address
    fields = [street, city, state, zip]
    fields.delete_if { |f| f.blank? }
    fields.join(", ")
  end

  def key_positions
    positions.where({volunteer_roles: {key_position: true}})
  end

  def regular_positions
    positions.where({volunteer_roles: {key_position: false}})
  end

  def shirts_needed
    shirts = Volunteer::Registration.joins(:profile).where(event_id: id).group(:shirt_size).count
    sizes = Profile.new.enums(:shirt_size).hash
    sorted = ActiveSupport::OrderedHash.new
    sizes.each do |key, label|
      sorted[label] = shirts[key.to_s] || 0
      shirts.delete(key.to_s)
    end

    sorted.merge(shirts)
  end

  def total_filled_positions
    total_positions_required - total_unfilled_positions
  end

  def total_positions_required
    positions.sum(&:needed_count)
  end

  def total_unfilled_positions
    counts = count_unfilled_positions
    unfilled_assignments = 0
    counts.each do |count|
      needed = count.needed.to_i
      assigned = count.assigned.to_i
      unfilled_assignments += needed - assigned
    end
    unfilled_assignments
  end

  def to_s
    name
  end

  def unassigned_volunteers
    volunteer_registrations.
        includes([:profile, :assignments]).
        where(volunteer_assignments: { registration_id: nil }).
        order("LOWER(profiles.last_name) ASC, LOWER(profiles.first_name) ASC")
  end

  def unfullfillment
    1.0 - fullfillment
  end

  def unused_roles
    if program.present?
      if positions.count > 0
        program.volunteer_roles.where("id NOT IN (?)", positions.map(&:role_id))
      else
        program.volunteer_roles
      end
    else
      []
    end
  end

  private

  def address_is_provided
    required_fields = [:street, :city, :state, :zip]
    errors.add_on_blank(required_fields)

    missing_fields = errors.keys & required_fields
    if missing_fields.present?
      humanize = missing_fields.map { |f| f.to_s.humanize }
      errors.add(:address, "is missing #{humanize.join(", ")}")
      false
    end
    true
  end
end

app/controllers/admin/events_controller.rb
class Admin::EventsController < Admin::BaseController
  before_filter :load_event, only: [:edit, :update, :show, :destroy]
  authorize_resource

  def index
    if @program.present?
      @events = @program.events.sorted
    else
      @events = Event.sorted
    end
  end

  def new
    @event = Event.new
    @event.program = @program if @program
  end

  def create
    @event = Event.new params[:event]
    @event.program = @program if @program.present?

    respond_to do |format|
      if @event.save
        format.html { redirect_to admin_event_path(@program, @event), notice: "Event created successfully." }
      else
        format.html { render 'new' }
      end
    end
  end

  def edit
    @event = Event.includes(:positions => :role).find params[:id]
  end

  def update
    respond_to do |format|
      if @event.update_attributes params[:event]
        format.html { redirect_to admin_event_path(@program, @event), notice: "Event updated successfully." }
      else
        format.html { render 'edit' }
      end
    end
  end

  def show
  end

  def destroy
    @event.destroy

    redirect_to admin_events_path(@program)
  end

  private

  def load_event
    if @program.present?
      @event = @program.events.find params[:id]
    else
      @event = Event.find params[:id]
    end
  end
end

app/controllers/volunteer/events_controller.rb
class Volunteer::EventsController < Volunteer::BaseController
  before_filter :authenticate_user!
  authorize_resource

  def index
    @events = Event.sorted
  end

  def show
    @event = Event.find params[:id]
    render layout: 'event'
  end
end

app/helpers/admin/events_helper.rb
module Admin::EventsHelper
  def link_to_add_fields(body, association, f, container, source, selection, html_options={})
    new_object = f.object.send(association).klass.new
    id = new_object.object_id
    fields = f.fields_for(association, new_object, child_index: id) do |builder|
      render(association.to_s.singularize + "_fields", f: builder)
    end

    html_options[:class] = "" if html_options[:class].nil?
    html_options[:class] = html_options[:class] + " add-fields"

    html_options[:data] = {} if html_options[:data].nil?
    html_options[:data].merge!({id: id, fields: fields.gsub("\n", ""), container: container, source: source, selection: selection})

    link_to body, '#', html_options
  end
end

app/helpers/volunteer/events_helper.rb
module Volunteer::EventsHelper
  def progress_class(value)
    case value
      when 0..0.5
        "warning"
      when 0.5..0.8
        "info"
      else
        "success"
    end
  end
end

app/views/admin/events/_event_row.html.erb
<tr>
  <td><%= link_to event.name, admin_event_path(@program, event) %></td>
  <td><%= l event.starts_at %></td>
  <td>
    <% if can? :edit, event %>
      <%= link_to edit_admin_event_path(@program, event),
                  class: "btn btn-small btn-primary" do %>
        <i class="icon-pencil icon-white"></i> Edit
      <% end %>
    <% end %>
    <% if can? :delete, event %>
      <%= link_to admin_event_path(@program, event),
                  method: :delete,
                  data: { confirm: 'Are you sure?' }, 
                  class: "btn btn-small btn-danger" do %>
        <i class="icon-trash icon-white"></i> Delete
      <% end %>
    <% end %>
  </td>
</tr>

app/views/admin/events/_events_table.html.erb
<table class="table">
  <tr>
    <th>Name</th>
    <th>Starts At</th>
    <th></th>
  </tr>

  <%= render partial: '/admin/events/event_row', collection: events, as: :event %>
</table>

app/views/admin/events/_form.html.erb
<%= simple_form_for event, url: url, html: { class: "form-horizontal" } do |f| %>
  <% unless @program.nil? %>
    <%= f.input :program_id, as: :hidden, input_html: {value: @program.id} %>
  <% end %>

  <ul class="nav nav-tabs" id="event_form_tabs">
    <li class="active"><%= link_to "Details", "#event_settings", data: { toggle: "tab" } %></li>
    <li><%= link_to "Volunteer Options", "#event_volunteer_settings", data: { toggle: "tab" } %></li>
  </ul>

  <div class="tab-content">
    <div class="tab-pane active" id="event_settings">
      <%= f.association :program unless @program %>
      <%= f.input :name %>
      <%= f.input :code, input_html: { class: "span1" } %>
      <%= f.input :starts_at, as: :datetime_picker, placeholder: "dd/mm/yyyy hh:mm pp", input_html: { class: "input-medium" } %>
      <%= f.input :venue %>
      <%= f.input :address, required: true do %>
        <div class="controls-row">
          <%= f.input_field :street, placeholder: "Street", class: "span5" %>
        </div>
        <div class="controls-row">
          <%= f.input_field :city, placeholder: "City", class: "span2" %>
          <%= f.input_field :state, collection: us_states, class: "span2" %>
          <%= f.input_field :zip, placeholder: "Zip", class: "span1" %>
        </div>
      <% end %>

      <fieldset>
        <legend>Logistics</legend>
        <%= f.input :participant_limit, input_html: {class: "input-mini"} %>
        <%= f.input :setup_at, as: :datetime_picker, placeholder: "dd/mm/yyyy hh:mm pp", input_html: { class: "input-medium" } %>
        <%= f.input :teardown_at, as: :datetime_picker, placeholder: "dd/mm/yyyy hh:mm pp", input_html: { class: "input-medium" } %>
      </fieldset>
    </div>
    <div class="tab-pane" id="event_volunteer_settings">
      <p>Todo, add volunteer positions form here</p>

      <%= f.input :positions do %>
        <div class="row">
          <span class="span3"><strong>Title</strong></span>
          <span class="span1"><strong>Needed</strong></span>
        </div>
        <div id="positions_list">
          <%= f.simple_fields_for :positions do |p| %>
            <%= render 'position_fields', f: p %>
          <% end %>

        </div>
        <% if @event.unused_roles.count > 0 %>
          <div class="row">
            <div class="span3">
              <%= select_tag "role",
                             options_from_collection_for_select(
                                     @event.unused_roles, 'id', 'title'),
                             class: "span3" %>
            </div>
            <div class="span1">
              <%= link_to_add_fields "Add",
                                     :positions,
                                     f,
                                     "#positions_list",
                                     admin_volunteer_role_path(@program, ":id:", format: :json),
                                     "#role",
                                     class: "btn btn-info btn-medium" %>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>


  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/admin/events/_position_fields.html.erb
<div id="position_<%= f.object.object_id %>" class="controls-row">
  <%= f.hidden_field :role_id %>
  <div class="row">
    <span class="span3"><%= f.object.role.try(:title) %></span>
    <%= f.text_field :needed_count, class: "span1", style: "text-align: center;" %>
    <%= f.hidden_field :_destroy %>
    <%= link_to "#", class: "span2 remove-fields" do %>
      <i class="icon-trash"></i> Remove
    <% end %>
  </div>
</div>

app/views/admin/events/edit.html.erb
<h2>Edit Event</h2>

<%= render 'form', event: @event, url: admin_event_path(@program, @event) %>

app/views/admin/events/index.html.erb
<%= link_to "New Event", new_admin_event_path(@program), class: "btn pull-right" %>

<h2>Events</h2>

<%= render 'events_table', events: @events %>

app/views/admin/events/new.html.erb
<h2>New Event</h2>

<%= render 'form', event: @event, url: admin_events_path(@program) %>

app/views/admin/events/show.html.erb
<h2><%= @event.name %></h2>

<dl class="dl-horizontal">
  <dt>When:</dt>
  <dd><%= l @event.starts_at %></dd>

  <dt>Where:</dt>
  <dd>
    <%= @event.venue %><br>
    <%= @event.street %><br>
    <%= @event.city %>, <%= @event.state %> <%= @event.zip %>
  </dd>
</dl>

<h3>Logistics</h3>

<dl class="dl-horizontal">
  <dt>Participant Limit:</dt>
  <dd><%= @event.participant_limit %></dd>

  <% if @event.setup_at.present? %>
    <dt>Setup at:</dt>
    <dd><%= l @event.setup_at %></dd>
  <% end %>

  <% if @event.teardown_at.present? %>
    <dt>Teardown at:</dt>
    <dd><%= l @event.teardown_at %></dd>
  <% end %>
</dl>

<%= link_to "<- Back", admin_events_path(@program) %> |
<%= link_to "Edit", edit_admin_event_path(@program, @event) %> |
<%= link_to "Delete", admin_event_path(@program, @event), method: :delete, confirm: "Are you sure?" %>