config/routes.rb
VirginiaFIRST::Application.routes.draw do

  resource :account, controller: "accounts", only: [:show, :edit, :update, :destroy], path_names: {edit: "settings"}

  scope module: 'accounts', path: 'account' do
    resource :profile, controller: "profiles", path: "personal", only: [:edit, :create, :update], as: "personal_profile"
    resource :background, controller: "profiles", only: [:edit, :create, :update], as: "background_profile"
    resource :volunteer, controller: "profiles", only: [:show, :edit, :update], as: "volunteer_profile"
    resource :mentor, controller: "profiles", only: [:show, :edit, :update], as: "mentor_profile"
    resource :experience, controller: "profiles", only: [:edit, :update], as: "experience_profile"
    get 'events' => 'registrations#index', as: 'my_events'
    delete 'events/:id' => 'registrations#destroy', as: 'delete_my_event'
  end

  namespace :ambassador do
    resource :registrations, path: 'register', only: [:new, :create, :show]
  end

  devise_for :users, controllers: {omniauth_callbacks: "omniauth_callbacks"}

  get 'home/events', as: 'upcoming_events'
  get 'home/faq', as: 'faq_home'
  get 'home/mentor', as: 'mentor_home'
  get 'home/volunteer', as: 'volunteer_home'

  get '/admin', to: redirect('/admin/events')
  scope module: 'admin', path: 'admin', as: 'admin' do
    scope path: '(/:program)' do
      resources :events
      resources :games
      scope module: 'volunteer', path: 'volunteer', as: 'volunteer' do
        resources :roles
      end
    end

    resources :skills
    resources :profiles, only: [:index, :show]
  end

  scope module: 'volunteer' do
    scope path: '(/:program)' do
      resource :registrations, path: 'register', as: 'volunteer_registration', only: [:new, :create, :show]
      resources :events, only: [:index, :show] do
        get 'profiles' => 'profiles#index'
        get 'reports/crew_break_down' => 'reports#crew_break_down', as: 'volunteer_break_down_report'
        get 'reports/nametags' => 'reports#nametags', as: 'volunteer_nametags_report'
        get 'reports/shirts' => 'reports#shirts', as: 'volunteer_shirts_report'
        get 'email_blast' => 'email_blast#show', as: 'email_blast'
        resources :check_in
      end
    end
    resources :assignments
    get 'profiles/:id' => 'profiles#show', as: 'profile'
  end

  root :to => 'home#index'

end

app/models/game.rb
class Game < ActiveRecord::Base
  belongs_to :program, class_name: "FirstProgram"
  has_many :events

  attr_accessible :ends_at, :logo, :name, :program_id, :season, :starts_at

  mount_uploader :logo, LogoUploader

  validates_presence_of :name
  validates_presence_of :program
  validates_presence_of :season
  validates_numericality_of :season, greater_than_or_equal_to: 1992, only_integer: true, allow_nil: true

  def to_s
    "#{season}:#{name}"
  end
end

app/controllers/admin/games_controller.rb
class Admin::GamesController < Admin::BaseController
  before_filter :load_game, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource

  def index
  end

  def show
  end

  def new
  end

  def create
    @game = Game.new params[:game]

    if params[:program].present?
      @program = FirstProgram.find_by_code params[:program]
      @game.program = @program
    end

    respond_to do |format|
      if @game.save
        format.html { redirect_to admin_games_path(@program), notice: "Game successfully created." }
      else
        format.html { render :new }
      end
    end
  end

  def edit
  end

  def update
    respond_to do |format|
      if @game.update_attributes params[:game]
        format.html { redirect_to admin_games_path(@program), notice: "Game successfully updated." }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @game.destroy

    redirect_to admin_games_path(@program), notice: "Game successfully deleted."
  end

  private

  def load_game
    if @program
      @game = @program.games.find params[:id]
    else
      @game = Game.find params[:id]
    end
  end
end

app/views/admin/games/_form.html.erb
<%= simple_form_for game, url: url, html: {class: "form-horizontal"} do |f| %>
  <%= f.error_notification %>

  <%= f.association :program unless @program %>
  <%= f.input :name, autofocus: true %>
  <%= f.input :season, input_html: {class: "input-mini"}%>
  <fieldset>
    <legend>Logo</legend>

    <% if game.logo.blank? %>
      <%= f.input :logo, as: :file, lable: false %>
    <% else %>
      <%= f.input :current_logo, label: "Current logo:" do %>
        <%= image_tag game.logo %>
      <% end %>
      <%= f.input :logo, as: :file, label: "New logo:" %>
    <% end %>
  </fieldset>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/admin/games/edit.html.erb
<h2>Edit Game</h2>

<%= render "form", game: @game, url: admin_game_path(@program, @game) %>

app/views/admin/games/index.html.erb
<%= link_to "New Game", new_admin_game_path(@program), class: "btn pull-right" %>

<h1>Games</h1>

<table class="table">
  <tr>
    <th></th>
    <th>Name</th>
    <th>Season</th>
    <th></th>
    <th></th>
  </tr>

  <% @games.each do |game| %>
    <tr>
      <td></td>
      <td>
        <%= link_to game.name, admin_game_path(@program, game) %>
      </td>
      <td><%= game.season %></td>
      <% if can? :edit, game %>
        <td class="action">
          <%= link_to edit_admin_game_path(@program, game), class: "btn btn-small btn-success" do %>
            <i class="icon-pencil icon-white"></i> Edit
          <% end %>
        </td>
      <% end %>
      <% if can? :delete, game %>
        <td>
          <%= link_to admin_game_path(@program, game), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-small btn-danger" do %>
            <i class="icon-trash icon-white"></i> Delete
          <% end %>
        </td>
      <% end %>
    </tr>
  <% end %>
</table>

app/views/admin/games/new.html.erb
<h2>New Game</h2>

<%= render "form", game: @game, url: admin_games_path(@program) %>

app/views/admin/games/show.html.erb
<h3 class="center"><%= @game.season %></h3>
<p>
  <%= image_tag @game.logo %>
</p>

<h3>Events</h3>

<%= render "admin/events/events_table", events: @game.events %>