config/routes.rb
VirginiaFIRST::Application.routes.draw do

  resource :account, controller: "accounts", only: [:show, :edit, :update, :destroy], path_names: {edit: "settings"}

  scope module: 'accounts', path: 'account' do
    resource :profile, controller: "profiles", path: "personal", only: [:edit, :create, :update], as: "personal_profile"
    resource :background, controller: "profiles", only: [:edit, :create, :update], as: "background_profile"
    resource :volunteer, controller: "profiles", only: [:show, :edit, :update], as: "volunteer_profile"
    resource :mentor, controller: "profiles", only: [:show, :edit, :update], as: "mentor_profile"
    resource :experience, controller: "profiles", only: [:edit, :update], as: "experience_profile"
    get 'events' => 'registrations#index', as: 'my_events'
    delete 'events/:id' => 'registrations#destroy', as: 'delete_my_event'
  end

  namespace :ambassador do
    resource :registrations, path: 'register', only: [:new, :create, :show]
  end

  devise_for :users, controllers: {omniauth_callbacks: "omniauth_callbacks"}

  get 'home/events', as: 'upcoming_events'
  get 'home/faq', as: 'faq_home'
  get 'home/mentor', as: 'mentor_home'
  get 'home/volunteer', as: 'volunteer_home'

  get '/admin', to: redirect('/admin/events')
  scope module: 'admin', path: 'admin', as: 'admin' do
    scope path: '(/:program)' do
      resources :events
      resources :games
      scope module: 'volunteer', path: 'volunteer', as: 'volunteer' do
        resources :roles
      end
    end

    resources :skills
    resources :profiles, only: [:index, :show]
  end

  scope module: 'volunteer' do
    scope path: '(/:program)' do
      resource :registrations, path: 'register', as: 'volunteer_registration', only: [:new, :create, :show]
      resources :events, only: [:index, :show] do
        get 'profiles' => 'profiles#index'
        get 'reports/crew_break_down' => 'reports#crew_break_down', as: 'volunteer_break_down_report'
        get 'reports/nametags' => 'reports#nametags', as: 'volunteer_nametags_report'
        get 'reports/shirts' => 'reports#shirts', as: 'volunteer_shirts_report'
        get 'email_blast' => 'email_blast#show', as: 'email_blast'
        resources :check_in
      end
    end
    resources :assignments
    get 'profiles/:id' => 'profiles#show', as: 'profile'
  end

  root :to => 'home#index'

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def events
    @upcoming_events = Event.upcoming
  end

  def faq
  end

  def index
    @upcoming_events = Event.upcoming
  end

  def mentor
  end

  def volunteer
    @roles = Volunteer::Role.limit(5).order("RANDOM()")
  end
end

app/helpers/home_helper.rb
module HomeHelper
  def display_location(event)
    buffer = ActiveSupport::SafeBuffer.new
    buffer << "<address>".html_safe
    buffer << "#{event.venue}<br>".html_safe if event.venue.present?
    buffer << "#{event.city}, #{event.state}"
    buffer << "</address>".html_safe
    buffer
  end
end

app/views/home/events.html.erb
<h1>Upcoming events</h1>
<br>
<p>
  Here's the list of upcoming events open for volunteers.
  If you're looking for the FRC Virginia Regional, you'll need to sign up
  using <%= first %>'s
  <%= link_to 'Volunteer Information & Matching System',
              'https://my.usfirst.org/vims/' %>
  in order to volunteer.
</p>

<div class="row">
  <div class="span6">
    <% @upcoming_events.each do |event| %>
      <div>
        <%= image_tag event.program.flag,
                      alt: event.program.name,
                      width: "100px",
                      class: "pull-left",
                      style: "margin-top: 10px" %>
        <div style="margin-left: 110px">
          <h3><%= event.name %></h3>
          <p>
            <strong><%= l event.starts_at, format: :date %></strong><br>
            <%= print_address event %>
          </p>
        </div>
        <div class="clearfix"></div>
      </div>
    <% end %>
  </div>

  <div class="span6">
    <div id="upcoming_events_map_canvas" data-events="<%= @upcoming_events.to_json %>"></div>
  </div>
</div>

app/views/home/faq.html.erb
<h1>Frequently Asked Questions</h1>

<p class="lead">Coming soon...</p>
<!--<dl>-->
  <!--<dt>Will I have time to watch the event?</dt>-->
  <!--<dd></dd>-->

  <!--<dt>Do I have to volunteer for the whole day?</dt>-->
  <!--<dd></dd>-->

  <!--<dt>What should I wear?</dt>-->
  <!--<dd></dd>-->

  <!--<dt>Will food be provided?</dt>-->
  <!--<dd></dd>-->

  <!--<dt>Can students volunteer at an event?</dt>-->
  <!--<dd>Absolutely! </dd>-->
<!--</dl>-->

app/views/home/index.html.erb
<h1>Volunteer Registration is open</h1>

<p>
  The new 2014-15 FTC CASCADE EFFECT season is in full swing.
  <%= virginia_first %> needs your help to make
  these competitions a success by volunteering to support our events.
</p>

<p>
  Volunteer registration for official <%= first %> events are managed in the
  <%= link_to 'Volunteer Information & Matching System',
              'https://my.usfirst.org/vims/' %>
  for both FTC and FRC this season. In order to volunteer for any of these
  events you must register online using
  <%= link_to 'VIMS', 'https://my.usfirst.org/vims/' %>. To learn more about
  how VIMS works and how to sign up, you can read the
  <%= link_to 'documentation',
              'https://my.usfirst.org//FIRSTPortal/VIMS/VIMSUserGuideJune2014.pdf' %>.
</p>

<div class="row">
  <div class="offset2 span4 center">
    <% frc = FirstProgram[:frc] %>
    <%= link_to "https://my.usfirst.org/vims/" do %>
      <%= image_tag frc.flag.medium, alt: frc.name %>
    <% end %>
  </div>

  <div class="span4 center">
    <% ftc = FirstProgram[:ftc] %>
    <%= link_to "https://my.usfirst.org/vims/" do %>
      <%= image_tag ftc.flag.medium, alt: ftc.name %>
    <% end %>
  </div>
</div>

<br>

<div class="row">
  <div class="span12">
    <div class="row section">
      <div class="span3">
        <h2 class="center">
          <%= link_to volunteer_home_path do %>
            Support<br>an event
          <% end %>
        </h2>
      </div>
      <div class="span9">
        <p>
          <%= virginia_first %> organizes events throughout the state of Virginia
          to inspire young people, from workshops to competitions. None of which
          would be successful without the support of our volunteers.
        </p>
        <p>
          Volunteers come from a wide variety of backgrounds
          and skills. You don't have to be a rocket science to help out.
          <%= link_to "Learn more", volunteer_home_path %> about our volunteer
          opportunities
        </p>
      </div>
    </div>

    <hr>

    <div class="row section">
      <div class="span9">
        <p>
          Mentors are the keystone of <%= first %> programs, using technical
          and non-technical experience to inspire students.
          <%= link_to "Learn more", mentor_home_path %> about mentoring a
          <%= first %> team.
        </p>
        <p>
          Looking for mentoring opportunities in Virginia? Sign up today and
          <%= virginia_first %> will connect you with a team in need.
        </p>
      </div>
      <div class="span3">
        <h2 class="center">
          <%= link_to mentor_home_path do %>
            Mentor<br>a team
          <% end %>
        </h2>
      </div>
    </div>
  </div>
</div>

app/views/home/mentor.html.erb
<h1>Become a Mentor!</h1>

<p>
  Mentors are the keystone of our programs. Mentors engage and inspire students
  in ways far beyond science and technology. They enable both students and
  adults to appreciate the value of sportsmanship, teamwork, and Gracious
  Professionalism<sup>®</sup>.

</p>

<p>
  An <strong>FTC Coach/Mentor</strong> works with his or her students by helping
  them to develop skills and to design and build a successful robot. They guide
  teams through any issues they encounter, making them stronger in both their
  school and personal lives.
</p>

<p>
  Click to read the <%= link_to 'FTC Mentor Guide', 'http://www.usfirst.org/sites/default/files/uploadedFiles/Robotics_Programs/FTC/FTC_Documents/2013-FTCMentorGuide.pdf' %>.
</p>

<p>
  <strong>FRC Mentors</strong> play a vital role in the success of their
  students. Mentors work extensively with team members during the build season,
  designing, building, and fabricating a functional robot for Competition. Their
  expertise is the catalyst for the team’s and students’ success. FRC Mentors
  are the major distinction between the FRC program and other robotic
  competitions as they are wholly the professional role model for the student.
</p>

<p>
  Click to read the <%= link_to 'FRC Mentor Guide', 'http://www3.usfirst.org/uploadedFiles/Community/FRC/Team_Resources/Mentoring%20Guide.pdf' %>.
</p>

app/views/home/volunteer.html.erb
<h1>Become a Volunteer!</h1>
<p class="lead">There are numerous way for you to join the fun</p>

<p>
  <%= virginia_first %> relies on the help of volunteers to support all of our
  programs, assist at our events and competitions, and plan for our future. From
  administrative help and writers to field attendants and media relations, our
  volunteers have a broad spectrum of talents. <%= virginia_first %>'s programs,
  operations, and competitions don't happen without hundreds of people just like
  you.
</p>

<p>
  <%= first %> is dedicated to promoting safety, and security for participants,
  volunteers, and staff who attend <%= first %> events. The procedures we have
  established protect you as a volunteer and <%= first %> as an organization.
</p>

<p>
  Check out our list of <%= link_to 'upcoming events', upcoming_events_path %>
  or <%= link_to 'register to volunteer', new_volunteer_registration_path %>
  today.
</p>

<h3>Requirements</h3>

<ul>
  <li>
    Event volunteers must be at least 13 years of age, however, some
    restrictions apply.
  </li>
  <li>
    Under 18 years of age, parent/guardian permission is required.
  </li>
</ul>

<h3>Volunteer Roles</h3>

<p>Here is a quick glane at a few of the roles that are needed for our events. </p>

<dl>
  <% @roles.each do |role| %>
    <dt><%= role.title %></dt>
    <dd><%= role.description %></dd>
  <% end %>
</dl>

<p>
  For a complete listing of volunteer positions and their descriptions, check out these resources:
</p>

<p>
  <%= link_to 'FTC Volunteer Roles', 'http://www.usfirst.org/roboticsprograms/ftc/first-tech-challenge-volunteer-opportunities' %>
</p>

<p>
  <%= link_to 'FRC Volunteer Roles', 'http://www.usfirst.org/community/volunteers/frc-volunteer-event-positions' %>
</p>